In [1]:
import pandas as pd
import matplotlib.pyplot as plt # 基础绘图库（什么都能画，但可能慢、复杂）
import seaborn as sns # 数据可视化专用库（专门用来快速画数据图）

# 忽略警告
import warnings
warnings.filterwarnings('ignore')

# 中文字体宋体，英文字体新罗马
plt.rcParams['font.sans-serif'] = ['SimHei']
plt.rcParams['font.serif'] = ['Times New Roman']
# 字体大小
plt.rcParams['font.size'] = 12  
# 正常显示负号
plt.rcParams['axes.unicode_minus'] = False

In [2]:
df = pd.read_excel('中间数据集\\表1与表2拼接后的数据集.xlsx')
df = df.drop(['纹饰', '采样位置', '颜色', '表面风化'], axis=1)
df.head()

,文物编号,类型,二氧化硅(SiO2),氧化钠(Na2O),氧化钾(K2O),氧化钙(CaO),氧化镁(MgO),氧化铝(Al2O3),氧化铁(Fe2O3),氧化铜(CuO),氧化铅(PbO),氧化钡(BaO),五氧化二磷(P2O5),氧化锶(SrO),氧化锡(SnO2),二氧化硫(SO2),风化具体情况
0,1,高钾,69.33,0.0,9.99,6.32,0.87,3.93,1.74,3.87,0.00,0.00,1.17,0.00,0.0,0.39,无风化
1,2,铅钡,36.28,0.0,1.05,2.34,1.18,5.73,1.86,0.26,47.43,0.00,3.57,0.19,0.0,0.00,风化
2,3,高钾,87.05,0.0,5.19,2.01,0.00,4.06,0.00,0.78,0.25,0.00,0.66,0.00,0.0,0.00,无风化
3,3,高钾,61.71,0.0,12.37,5.87,1.11,5.50,2.16,5.09,1.41,2.86,0.70,0.10,0.0,0.00,无风化
4,4,高钾,65.88,0.0,9.67,7.12,1.56,6.44,2.06,2.18,0.00,0.00,0.79,0.00,0.0,0.36,无风化

In [3]:
import pandas as pd

# 假设df是你的数据集DataFrame，category_column是分类列的名称
# 首先，找出所有不同的类别
categories = df["风化具体情况"].unique()

# 然后，为每个类别创建一个空的DataFrame
category_datasets = {category: pd.DataFrame() for category in categories}

# 遍历原始数据集，并将每个记录分配到相应的类别DataFrame中
for category in categories:
    category_datasets[category] = df[df["风化具体情况"] == category]

df1 = category_datasets["风化"]
df2 = category_datasets["无风化"]

In [4]:
import pandas as pd

# 假设df是你的数据集DataFrame，category_column是分类列的名称
# 首先，找出所有不同的类别
categories = df1["类型"].unique()

# 然后，为每个类别创建一个空的DataFrame
category_datasets = {category: pd.DataFrame() for category in categories}

# 遍历原始数据集，并将每个记录分配到相应的类别DataFrame中
for category in categories:
    category_datasets[category] = df1[df1["类型"] == category]

# 风化的高钾玻璃
df_1_k = category_datasets["高钾"].drop(["类型", "风化具体情况"], axis=1)
# 风化的铅钡玻璃
df_1_b = category_datasets["铅钡"].drop(["类型", "风化具体情况"], axis=1)

In [5]:
import pandas as pd

# 假设df是你的数据集DataFrame，category_column是分类列的名称
# 首先，找出所有不同的类别
categories = df2["类型"].unique()

# 然后，为每个类别创建一个空的DataFrame
category_datasets = {category: pd.DataFrame() for category in categories}

# 遍历原始数据集，并将每个记录分配到相应的类别DataFrame中
for category in categories:
    category_datasets[category] = df2[df2["类型"] == category]

# 未风化的高钾玻璃
df_2_k = category_datasets["高钾"].drop(["类型", "风化具体情况"], axis=1)
# 未风化的铅钡玻璃
df_2_b = category_datasets["铅钡"].drop(["类型", "风化具体情况"], axis=1)

In [6]:
res = pd.DataFrame({
            "未风化高钾玻璃": (df_2_k.drop("文物编号", axis=1)).mean(),
            "未风化铅钡玻璃": (df_2_b.drop("文物编号", axis=1)).mean(),
            "风化高钾玻璃": (df_1_k.drop("文物编号", axis=1)).mean(),
            "风化铅钡玻璃": (df_1_b.drop("文物编号", axis=1)).mean()
            })

res["高钾玻璃风化前比风化后"] = (res["未风化高钾玻璃"]) / res["风化高钾玻璃"]
res["铅钡玻璃风化前比风化后"] = (res["未风化铅钡玻璃"]) / res["风化铅钡玻璃"]
res

,未风化高钾玻璃,未风化铅钡玻璃,风化高钾玻璃,风化铅钡玻璃,高钾玻璃风化前比风化后,铅钡玻璃风化前比风化后
二氧化硅(SiO2),67.984167,54.980000,93.963333,26.797143,0.723518,2.051711
氧化钠(Na2O),0.695000,1.299048,0.000000,0.608571,inf,2.134585
氧化钾(K2O),9.330833,0.215714,0.543333,0.141786,17.173313,1.521411
氧化钙(CaO),5.332500,1.408571,0.870000,2.531071,6.129310,0.556512
氧化镁(MgO),1.079167,0.594286,0.196667,0.683929,5.487288,0.868930
氧化铝(Al2O3),6.620000,4.442857,1.930000,3.086071,3.430052,1.439648
氧化铁(Fe2O3),1.931667,0.806667,0.265000,0.542857,7.289308,1.485965
氧化铜(CuO),2.452500,1.311429,1.561667,2.305714,1.570438,0.568773
氧化铅(PbO),0.411667,22.188095,0.000000,41.720000,inf,0.531834
氧化钡(BaO),0.598333,8.842381,0.000000,11.726429,inf,0.754056
五氧化二磷(P2O5),1.402500,1.145238,0.280000,4.903214,5.008929,0.233569
氧化锶(SrO),0.041667,0.277143,0.000000,0.401071,inf,0.691006
氧化锡(SnO2),0.196667,0.050952,0.000000,0.063571,inf,0.801498
二氧化硫(SO2),0.101667,0.174286,0.000000,1.268571,inf,0.137387

In [7]:
# 按比例推算高钾玻璃风化前成分
result_1 = (df_1_k.drop("文物编号", axis=1)) * res['高钾玻璃风化前比风化后']

result_1['氧化钠(Na2O)'].fillna(0.695000, inplace=True)
result_1['氧化铅(PbO)'].fillna(0.411667, inplace=True)
result_1['氧化钡(BaO)'].fillna(0.598333, inplace=True)
result_1['氧化锶(SrO)'].fillna(0.041667, inplace=True)
result_1['氧化锡(SnO2)'].fillna(0.196667, inplace=True)
result_1['二氧化硫(SO2)'].fillna(0.101667, inplace=True)

result_1["文物编号"] = df_1_k["文物编号"]
result_1.head()

,二氧化硅(SiO2),氧化钠(Na2O),氧化钾(K2O),氧化钙(CaO),氧化镁(MgO),氧化铝(Al2O3),氧化铁(Fe2O3),氧化铜(CuO),氧化铅(PbO),氧化钡(BaO),五氧化二磷(P2O5),氧化锶(SrO),氧化锡(SnO2),二氧化硫(SO2),文物编号
8,67.019476,0.695,0.000000,6.558362,0.000000,6.791503,1.239182,5.088218,0.411667,0.598333,3.055446,0.041667,0.196667,0.101667,7
11,68.748684,0.695,10.132255,3.800172,0.000000,4.527668,2.332579,2.434178,0.411667,0.598333,1.753125,0.041667,0.196667,0.101667,9
12,70.014841,0.695,15.799448,1.287155,0.000000,2.778342,1.895220,1.319168,0.411667,0.598333,0.000000,0.041667,0.196667,0.101667,10
14,68.220516,0.695,17.345046,4.413103,0.000000,5.007876,2.113899,2.591222,0.411667,0.598333,0.751339,0.041667,0.196667,0.101667,12
22,66.816891,0.695,12.708252,10.174655,3.511864,12.005181,2.551258,0.863741,0.411667,0.598333,1.051875,0.041667,0.196667,0.101667,22

In [8]:
# 按比例推算铅钡玻璃风化前成分
result_2 = (df_1_b.drop("文物编号", axis=1)) * res['铅钡玻璃风化前比风化后']
result_2["文物编号"] = df_1_b["文物编号"]
result_2.head()

,二氧化硅(SiO2),氧化钠(Na2O),氧化钾(K2O),氧化钙(CaO),氧化镁(MgO),氧化铝(Al2O3),氧化铁(Fe2O3),氧化铜(CuO),氧化铅(PbO),氧化钡(BaO),五氧化二磷(P2O5),氧化锶(SrO),氧化锡(SnO2),二氧化硫(SO2),文物编号
1,74.436085,0.0,1.597481,1.302238,1.025337,8.249184,2.763895,0.147881,25.224865,0.000000,0.833841,0.131291,0.0,0.000000,2
9,41.321465,0.0,0.000000,0.823638,0.000000,1.929129,0.000000,5.920929,15.252986,23.549161,0.838512,0.255672,0.0,0.354459,8
10,9.458389,0.0,0.000000,1.775273,0.000000,1.598009,0.000000,1.785948,17.257998,23.089187,1.765780,0.366233,0.0,2.064932,8
13,68.916982,0.0,0.319496,1.953357,0.616940,3.872654,0.000000,2.804052,13.503254,11.016755,2.190876,0.255672,0.0,0.000000,11
19,60.812722,0.0,0.000000,1.630580,0.512668,5.139544,1.976333,1.996394,22.773112,4.034198,2.062413,0.131291,0.0,0.000000,19

In [9]:
# 将两个DataFrame上下合并
result_final = pd.concat([result_1, result_2], ignore_index=True)
result_final = result_final[["文物编号", "二氧化硅(SiO2)", "氧化钠(Na2O)", "氧化钾(K2O)", 
                    "氧化钙(CaO)", "氧化镁(MgO)", "氧化铝(Al2O3)", "氧化铁(Fe2O3)", 
                    "氧化铜(CuO)", "氧化铅(PbO)", "氧化钡(BaO)", "五氧化二磷(P2O5)",
                    "氧化锶(SrO)", "氧化锡(SnO2)", "二氧化硫(SO2)"]]
result_final.head()

,文物编号,二氧化硅(SiO2),氧化钠(Na2O),氧化钾(K2O),氧化钙(CaO),氧化镁(MgO),氧化铝(Al2O3),氧化铁(Fe2O3),氧化铜(CuO),氧化铅(PbO),氧化钡(BaO),五氧化二磷(P2O5),氧化锶(SrO),氧化锡(SnO2),二氧化硫(SO2)
0,7,67.019476,0.695,0.000000,6.558362,0.000000,6.791503,1.239182,5.088218,0.411667,0.598333,3.055446,0.041667,0.196667,0.101667
1,9,68.748684,0.695,10.132255,3.800172,0.000000,4.527668,2.332579,2.434178,0.411667,0.598333,1.753125,0.041667,0.196667,0.101667
2,10,70.014841,0.695,15.799448,1.287155,0.000000,2.778342,1.895220,1.319168,0.411667,0.598333,0.000000,0.041667,0.196667,0.101667
3,12,68.220516,0.695,17.345046,4.413103,0.000000,5.007876,2.113899,2.591222,0.411667,0.598333,0.751339,0.041667,0.196667,0.101667
4,22,66.816891,0.695,12.708252,10.174655,3.511864,12.005181,2.551258,0.863741,0.411667,0.598333,1.051875,0.041667,0.196667,0.101667

In [10]:
result_final.to_excel("结果\\1_3_第一题第三问的奇葩预测.xlsx")